name: build
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - run: npx lerna bootstrap --hoist
    - run: npm run build
      env:
        RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
    - run: npm run lint
    - run: npm test
    - run: npm run test-package
